# Generated by Django 2.2.1 on 2019-05-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(max_length=250)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Section')),
            ],
        ),
    ]
