# Generated by Django 2.2.1 on 2019-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_color',
            field=models.CharField(default='#656C6C', max_length=250),
        ),
    ]
