# Generated by Django 2.2.1 on 2019-06-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_description',
            field=models.CharField(default='No description provided.', max_length=250),
        ),
    ]
