# Generated by Django 2.2.1 on 2019-07-22 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_section_section_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deck_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('strip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strip_title', models.CharField(max_length=250)),
                ('strip_altText', models.CharField(max_length=447)),
                ('strip_decks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_strips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Strip'),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Tag'),
        ),
    ]
