# Generated by Django 2.2.1 on 2019-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190722_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/frames/'),
        ),
    ]
