# Generated by Django 2.2.1 on 2019-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190729_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strip',
            name='strip_frames',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_strips',
            field=models.ManyToManyField(to='portfolio.Strip'),
        ),
    ]
