# Generated by Django 2.2.1 on 2019-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190729_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_strips',
        ),
        migrations.AddField(
            model_name='strip',
            name='strip_frames',
            field=models.ManyToManyField(to='portfolio.Frame'),
        ),
    ]
